# Generated by Django 3.0.1 on 2019-12-30 16:33

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Todo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField()),
                ('priority', models.PositiveSmallIntegerField(choices=[(1, 'Max'), (2, 'Not so max'), (3, 'Medium'), (4, 'So so'), (5, 'Low')])),
            ],
        ),
    ]
