# Generated by Django 3.0.1 on 2020-02-06 17:20

from django.db import migrations


def my_migration_logic(apps, schema_editor):
    Post = apps.get_model('core', 'Post')
    Post.objects.all().update(title='qwe')


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(my_migration_logic)
    ]
